quarkus:
  kubernetes:
    ports:
      - debug:
        container-port: 5005
        protocol: TCP
    env:
      configmaps: test-config
      vars:
        quarkus.kubernetes-config.enabled: "true"
        JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
  kubernetes-config:
    config-maps: test-config